#!/bin/env bash

if [[ $EUID == 0  ]]; then
  echo "This script can't be run as root! Please run it as a normal user"
  exit 1
fi

echo "Deleting old API builds..."
rm -rf ../dist/api || echo "cant delete old API build. Ignoring..."
echo "Creating API build directory..."
mkdir -p ../dist/api || echo "Cant create API build directory :( Maybe there is a file with the same name? Ignoring..."
echo "Building API..."
echo "----------------------------------"
../.venv/bin/python -m build ../src/api --outdir ../dist/api
BUILD_EXIT_CODE=$?
echo "----------------------------------"
echo "Build exited with code $BUILD_EXIT_CODE"

if [[ $BUILD_EXIT_CODE != 0 ]]; then
  echo "API build failed :("
  exit 1
fi

echo "API build completed!"
exit 0